theme: minima
title: Giordana Mecagni
author: GitHub User
description: > # this means to ignore newlines until "baseurl:"
  I am a person who has needs and loves a cat. 
# social links
twitter_username:  gmecagni
github_username:  gmecagni
show_excerpts: true # set to false to remove excerpts on the homepage
